# Generated by Django 3.2 on 2022-10-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='auteur',
        ),
    ]
