# Generated by Django 3.2 on 2022-10-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20221010_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
